# Generated by Django 3.0.2 on 2020-02-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupid', models.AutoField(db_column='GroupID', primary_key=True, serialize=False)),
                ('groupname', models.CharField(db_column='GroupName', max_length=255)),
            ],
            options={
                'db_table': 'Groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iteminlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ischecked', models.IntegerField(db_column='IsChecked')),
            ],
            options={
                'db_table': 'ItemInList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemid', models.AutoField(db_column='ItemID', primary_key=True, serialize=False)),
                ('itemname', models.CharField(blank=True, db_column='ItemName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memberofgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'MemberOfGroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoppinglists',
            fields=[
                ('listid', models.AutoField(db_column='ListID', primary_key=True, serialize=False)),
                ('listname', models.CharField(blank=True, db_column='ListName', max_length=255, null=True)),
                ('iscomplete', models.IntegerField(db_column='IsComplete')),
            ],
            options={
                'db_table': 'ShoppingLists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('avatar', models.CharField(blank=True, db_column='Avatar', max_length=255, null=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
