# Generated by Django 3.0.2 on 2020-02-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apigroups_apiuser_apiusergrouprelations_authgroup_authgrouppermissions_authpermission_authuser_authu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiGroups',
        ),
        migrations.DeleteModel(
            name='ApiUser',
        ),
        migrations.DeleteModel(
            name='ApiUsergroupRelations',
        ),
    ]
