# Generated by Django 3.0.3 on 2020-03-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200211_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membercontribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.IntegerField(db_column='Contribution')),
            ],
            options={
                'db_table': 'MemberContribution',
                'managed': False,
            },
        ),
    ]
